export {
  playerSpawnPose,
  practiceFieldRobots,
  buildFieldRobotCatalog,
  buildFieldRobotRenderStates,
  createNpcMotionStates,
  matchRobotSnapshots,
  BLUE_FAR_SPAWN,
  ALLIANCE_NEAR_SPAWN,
  RED_NEAR_SPAWN,
  RED_FAR_SPAWN,
  RED_BASE_PARK,
  BLUE_BASE_PARK,
  DEFAULT_PRACTICE_TEAMS,
  PLAYER_ROBOT_ID,
  CLAIMABLE_ROBOT_IDS,
  LOBBY_SLOT_ORDER,
  ROBOT_SLOT_LABELS,
  isClaimableRobotId,
  type ClaimableRobotId,
  type NpcMotionState,
  type MatchAlliance,
  type PracticeTeamNumbers,
  type MatchRobotLayout,
  type FieldRobotCatalogEntry,
  type FieldRobotRenderState,
} from '@ftc-sim/session';
